server:
  port: 10010


# DataSource Config
# springboot 2.0 连接Redis底层不是Jedis而是Lettuce
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


# 扫描xml所在位置
# 包下的实体可以使用类名代替全类名
# 启动时检查本地xml位置是否存在
# 执行器：为每一个语句执行创建一个新的预处理语句
# xml修改时自动刷新，无需重启
# 控制台打印执行sql，开发时使用
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.frog.entity
  check-config-location: true
  executor-type: simple
  global-config:
    db-config:
      id-type: input
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



